package dam.pmdm.pqrst.domain.model

/**
 * Domain model representing a generated PDF report for a consultation (RF-08).
 *
 * This is a **pure domain entity** — no Room annotations or Android framework imports belong here.
 * The data layer maps between this class and the corresponding Room entity.
 *
 * ### File-based storage strategy
 * The actual PDF content is **not** stored in the database. The rendered file is written to the
 * device's shared storage (via `FileProvider`) and only the path is recorded here in [pdfPath].
 * This mirrors the strategy used for ECG samples ([EcgRecord.filePath]) and keeps the database
 * lean. The file is shared via the Android share sheet (Drive, e-mail, etc.) using the URI
 * returned by [dam.pmdm.pqrst.domain.repository.ReportRepository.generatePdf].
 *
 * ### Report content (RF-08)
 * The PDF includes:
 * - Patient demographic data.
 * - Consultation summary (date, symptoms, vital signs, notes).
 * - ECG waveform image (the PNG snapshot at [EcgRecord.snapshotPath]).
 * - Analysis parameters from [EcgAnalysis] (BPM, R-peaks, regularity).
 * - Pattern comparison result from [Comparison] / [PatternMatch], if available.
 *
 * ### Format field
 * [format] is always `"PDF"` in the current implementation. It is persisted to leave the door
 * open for future export formats (e.g. `"HTML"`, `"CSV"`) without a schema migration.
 *
 * @property id Auto-incremented primary key. Defaults to 0 for unsaved (transient) instances.
 * @property consultationId Foreign key referencing [Consultation.id].
 * @property generatedAt ISO-8601 date-time when the report was generated, set by the data layer.
 * @property format Output format identifier. Always `"PDF"` in the current implementation.
 * @property summary Optional plain-text abstract included at the top of the report. May be omitted
 *   for simple reports or auto-generated by the data layer.
 * @property pdfPath Absolute path to the generated PDF file on device storage. `null` until the
 *   file has been fully written (i.e. the [Report] instance stored in the database before
 *   generation completes should not be used directly from the UI).
 * @property createdBy [AppUser.id] of the user who triggered report generation.
 */
data class Report(
    val id: Long = 0,
    val consultationId: Long,
    val generatedAt: String = "",
    val format: String = "PDF",
    val summary: String? = null,
    val pdfPath: String? = null,
    val createdBy: Long? = null,
)
